services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 9091:9091
    volumes:
      - /app
      - /app/node_modules
    networks:
      - ucomand-network-test

networks:
  ucomand-network-test:
    external: true
