services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 8081:8081
    volumes:
      - /app
      - /app/node_modules
    networks:
      - ucomand-network

networks:
  ucomand-network-test:
    external: true
