# version: '3.1'
# services:
#   frontend:
#     build:
#       context: ./Frontend-ucomand
#       dockerfile: Dockerfile-frontend
#     ports:
#       - 80:80
#     volumes:
#       - ./Frontend-ucomand:/app
#       - /app/node_modules

services:
  frontend:
    build:
      context: ./Frontend-ucomand
      dockerfile: Dockerfile-frontend
    ports:
      - 80:80
    volumes:
      - ./Frontend-ucomand:/app
      - /app/node_modules

  ucomand-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    env_file:
      - ./.env
    depends_on:
      - ucomand-database


  ucomand-database:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ucomand-database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ucomand
      POSTGRES_PASSWORD: ucomand
      POSTGRES_DB: ucomand-db

  # #Контейнер нужен для тестирования авторизации через телеграм. На проде должен быть отключен
  # ucomand-ngrok:
  #   #TDOO захардкодить версию
  #   image: ngrok/ngrok:latest
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   network_mode: host

volumes:
  ucomand-database_data:

