# services:

#   frontend:
#     build:
#       context: ./
#       dockerfile: Dockerfile-frontend
#     ports:
#       - 8081:8081
#     volumes:
#       - /app
#       - /app/node_modules
#     networks:
#       - ucomand-network

services:

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 80:80
    volumes:
      - /app
      - /app/node_modules
    networks:
      - ucomand-network
# networks:
#   ucomand-network:
#     external: true
