import { AbstractControl, ValidatorFn } from '@angular/forms';

export function forbiddenWordsValidator(): ValidatorFn {
  return (control: AbstractControl): { [key: string]: any } | null => {
    const value = control.value || '';
    const hasForbiddenWord = errorList.some(word => value.includes(word));
    return hasForbiddenWord ? { 'forbiddenWords': { value } } : null;
  };
}


const errorList = [
    "ocpio", "settings", "bookmarks", "contest", "help", "about", "my_notes",
    "messages", "super_search", "search", "note", "support", "editor", "profile",
    "contact", "schedule", "pays", "services", "gallery", "privacy_policy", "cabinet",
    "reviews", "blacklist", "create-service", "notifications", "group", "subscription",
    "mobile_app", "beauty", "tourism", "education", "media", "it", "Events", "Repair",
    "rental", "pets", "homeservice", "delivery", "automoto", "build", "health", "sport",
    "esoterics", "like", "album", "albums", "photo", "video", "direct", "sitemap",
    "history", "client", "docs", "archive", "vk", "yandex", "ok", "booking", "bnovo",
    "vipservice", "ostrovok", "onetwotrip", "ozon", "tutu", "101hotels", "hotels", "hotel",
    "travel", "2gis", "skyscanner", "bronevik", "trivago", "tripadvisor", "hotellook",
    "aviasales", "tinkoff", "mobile", "check", "day", "week", "month", "century", "season",
    "autumn", "winter", "spring", "summer", "morning", "noon", "afternoon", "midday",
    "evening", "night", "midnight", "moment", "second", "minute", "hour", "now", "never",
    "forever", "soon", "always", "already", "yet", "just", "usually", "after", "today",
    "yesterday", "tomorrow", "tonight", "before", "after", "again", "Monday", "Tuesday",
    "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "January", "February", "March",
    "April", "May", "June", "July", "August", "September", "October", "November", "December",
    "zero", "one", "first", "two", "second", "three", "third", "four", "fourth", "five",
    "fifth", "six", "sixth", "seventh", "seven", "eight", "nine", "ninth", "ten", "tenth",
    "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
    "nineteen", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety",
    "hundred", "thousand", "million", "billion", "number", "figure", "quantity", "couple",
    "person", "people", "man", "men", "woman", "women", "child", "children", "boy", "girl",
    "guy", "parents", "father", "mother", "son", "daughter", "brother", "sister",
    "grandfather", "grandmother", "family", "relationship", "husband", "wife", "uncle", "aunt",
    "nephew", "niece", "cousin", "friend", "neighbour", "name", "surname", "address", "age",
    "old", "young", "adult", "married", "unmarried", "single", "divorced", "life", "death",
    "body", "head", "face", "eye", "nose", "shoulder", "mouth", "hand", "arm", "leg", "foot",
    "heart", "hair", "skin", "blood", "thight", "health", "vision", "appearance", "height",
    "tall", "short", "thin", "thick", "fat", "nice", "beautiful", "ugly", "feeling", "love",
    "joy", "fear", "shame", "sadness", "anger", "care", "lie", "beauty", "pain", "kind",
    "active", "strong", "calm", "serious", "clever", "smart", "stupid", "poor", "rich",
    "interesting", "good", "happy", "dead", "wise", "clothes", "jeans", "trousers", "pants",
    "dress", "shirt", "skirt", "shorts", "jacket", "coat", "T-shirt", "blouse", "sweater",
    "scarf", "shoes", "boots", "hat", "cap", "sock", "glove", "suit", "underwear", "size",
    "image", "job", "work", "profession", "career", "teacher", "musician", "seller",
    "businessman", "artist", "doctor", "journalist", "worker", "farmer", "actor", "actress",
    "author", "writer", "manager", "military", "cook", "driver", "assistant", "singer",
    "lawyer", "waiter", "training", "question", "answer", "skill", "advice", "experience",
    "firm", "company", "business", "document", "data", "information", "case", "process",
    "offer", "decision", "reason", "opportunity", "shop", "market", "office", "boss",
    "colleague", "meeting", "police", "hospital", "bank", "cabinet", "success", "money",
    "situation", "accident", "problem", "aim", "goal", "result", "vacation", "art", "song",
    "picture", "idea", "thought", "society", "politics", "website", "email", "link", "network",
    "hobby", "game", "sport", "power", "student", "university", "school", "college", "lesson",
    "knowledge", "education", "science", "book", "copybook", "page", "pencil", "pen", "grammar",
    "speaking", "article", "learning", "school uniforms", "course", "word", "noun", "verb",
    "modal verb", "adjective", "sentence", "subject", "homework", "table", "practice", "English",
    "Russian", "task", "rule", "theory", "list", "dictionary", "vocabulary", "content",
    "paper", "bell", "behaviour", "stage", "option", "degree", "test", "exercise", "exam",
    "statement", "mistake", "memory", "part", "example", "lexicon", "history", "literature",
    "math", "music", "note", "holidays", "journal", "magazine", "base", "story", "group",
    "choice", "point", "colour", "light", "dark", "bright", "white", "black", "silver",
    "gold", "clean", "dirty", "good", "well", "bad", "big", "small", "huge", "average",
    "cheap", "expensive", "free", "hard", "soft", "smooth", "warm", "cold", "hot", "new",
    "normal", "open", "closed", "natural", "medical", "long", "short", "full", "great",
    "important", "political", "quick", "ready", "regular", "right", "left", "wrong",
    "difficult", "simple", "round", "modern", "social", "responsible", "probable", "next",
    "different", "easy", "foreign", "real", "amazing", "far", "close", "main", "last",
    "only", "available", "elementary", "general", "same", "some", "current", "public",
    "perfect", "most", "be", "have", "do", "say", "get", "find", "tell", "ask", "use",
    "come", "know", "go", "make", "give", "want", "look", "think", "take", "see", "work",
    "try", "leave", "need", "seem", "become", "call", "feel", "put", "keep", "help",
    "begin", "walk", "close", "open", "let", "grow", "mean", "believe", "play", "happen",
    "include", "set", "hear", "change", "create", "appear", "disappear", "stand", "sit",
    "serve", "run", "remember", "buy", "bring", "win", "learn", "live", "continue", "meet",
    "show", "allow", "write", "read", "lose", "offer", "follow", "teach", "pay", "speak",
    "stop", "start", "finish", "watch", "develop", "choose", "remember", "call", "try",
    "exist", "belong", "act", "reduce", "wait", "exist", "resist", "rise", "apply",
    "control", "reach", "risk", "wait", "cost", "develop", "progress", "result",
    "invest", "apply", "manage", "present", "prove", "affect", "consider", "influence",
    "achieve", "represent", "grow", "increase", "succeed", "obtain", "produce", "support",
    "guide", "handle", "recover", "resolve", "admit", "debate", "solve", "defend", "reject",
    "recommend", "introduce", "emphasize", "confirm", "discuss", "avoid", "focus", "reflect",
    "explain", "continue", "change", "create", "evaluate", "comment", "recommend", "refuse",
    "consider", "manage", "report", "suggest", "reflect", "describe", "describe", "debate",
    "limit", "calculate", "mention", "address", "argue", "update", "announce", "improve",
    "recognize", "demonstrate", "investigate", "determine", "interpret", "interpret", "document"
];
